spring.application.name=server
# 1. Database Connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORACLE
spring.datasource.username=HRMANAGEMENT
spring.datasource.password=Oracle@123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 2. Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# 3. Prevent the Spring AI Crash
spring.ai.vectorstore.oracle.enabled=false
